<?php
$_viewData = Mage::getSingleton('core/session')->getViewdata();
$_helper = $this->helper('catalog/output');
$_sortUrl = Mage::getBaseUrl() . $this->_nameInLayout . '?sort=' . ($this->getRequest()->getParam('sort') == 'DESC' ? 'ASC' : 'DESC');
$_sortText = $this->getRequest()->getParam('sort') == 'DESC' ? 'descending' : 'ascending';
?>
<h3>
    <a href="<?php echo $_sortUrl ?>">
        <?php echo $this->__('Viewing collection sorted ' . $_sortText . ' by weirdness rating (position)') ?></a>
</h3>
<p class="note-msg">Products courtesy of <a target="_blank"
                                            href="http://consequenceofsound.net/2013/07/the-25-weirdest-pieces-of-band-merchandise/">'The
        25 Weirdest Pieces of Band Merchandise'</a></p>
<div class="category-products">
    <ol class="products-list" id="products-list">
        <?php
        foreach ($_viewData['productCollection'] as $_product):
            ?>
            <?php $_iterator = 0; ?>
            <li class="item<?php if (++$_iterator == sizeof($_viewData['productCollection'])): ?> last<?php endif; ?>">
                <a href="<?php echo $_product->getProductUrl() ?>"
                   title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
                   class="product-image" style="width:300px"><img
                        src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')
                            ->resize(300); ?>"
                        alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/></a>

                <div class="product-shop">
                    <div class="f-fix">
                        <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                        <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>"
                                                    title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?></a>
                        </h2>
                        <?php if ($_product->getRatingSummary()): ?>
                            <?php echo $this->getReviewsSummaryHtml($_product) ?>
                        <?php endif; ?>

                        <small style="color:#3399cc">Weirdness rating: <?php echo $_product->getPos(); ?></small>
                        <br>
                        <?php echo Mage::helper('core')->currency($_product->getPrice(), true, false); ?>
                        <?php if ($_product->isSaleable()): ?>
                            <p>
                                <button type="button"
                                        title="<?php echo Mage::helper('core')->quoteEscape($this->__('Add to Cart')) ?>"
                                        class="button btn-cart"
                                        onclick="setLocation('<?php echo $this->helper('checkout/cart')->getAddUrl($_product) ?>')">
                                    <span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                            </p>
                        <?php else: ?>
                            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span>
                            </p>
                        <?php endif; ?>
                        <div class="desc std">
                            <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                            <br>
                            <a href="<?php echo $_product->getProductUrl() ?>"
                               title="<?php echo $_productNameStripped ?>"
                               class="link-learn"><?php echo $this->__('Learn More') ?></a>
                        </div>
                    </div>
                </div>
            </li>
        <?php endforeach; ?>
    </ol>
</div>
